In [1]:
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [6]:
# 현재경로 확인
os.getcwd()

'/content'

In [7]:
# 데이터 불러오기
data = pd.read_csv("/content/drive/MyDrive/패캠 머신러닝/4주차 앙상블/2. Data/otto_train.csv") # Product Category
data.head() # 데이터 확인

id  feat_1  feat_2  feat_3  ...  feat_91  feat_92  feat_93   target
0   1       1       0       0  ...        0        0        0  Class_1
1   2       0       0       0  ...        0        0        0  Class_1
2   3       0       0       0  ...        0        0        0  Class_1
3   4       1       0       0  ...        0        0        0  Class_1
4   5       0       0       0  ...        0        0        0  Class_1

[5 rows x 95 columns]

In [8]:
'''
id: 고유 아이디
feat_1 ~ feat_93: 설명변수
target: 타겟변수 (1~9)
'''

'\nid: 고유 아이디\nfeat_1 ~ feat_93: 설명변수\ntarget: 타겟변수 (1~9)\n'

In [9]:
nCar = data.shape[0] # 데이터 개수
nVar = data.shape[1] # 변수 개수
print('nCar: %d' % nCar, 'nVar: %d' % nVar )

nCar: 61878 nVar: 95


## 의미가 없다고 판단되는 변수 제거

In [10]:
data = data.drop(['id'], axis = 1) # id 제거

In [11]:
data

feat_1  feat_2  feat_3  feat_4  ...  feat_91  feat_92  feat_93   target
0           1       0       0       0  ...        0        0        0  Class_1
1           0       0       0       0  ...        0        0        0  Class_1
2           0       0       0       0  ...        0        0        0  Class_1
3           1       0       0       1  ...        0        0        0  Class_1
4           0       0       0       0  ...        0        0        0  Class_1
...       ...     ...     ...     ...  ...      ...      ...      ...      ...
61873       1       0       0       1  ...        0        2        0  Class_9
61874       4       0       0       0  ...        0        1        0  Class_9
61875       0       0       0       0  ...        0        0        0  Class_9
61876       1       0       0       0  ...        3       10        0  Class_9
61877       0       0       0       0  ...        0        2        0  Class_9

[61878 rows x 94 columns]

## 타겟 변수의 문자열을 숫자로 변환

In [12]:
mapping_dict = {"Class_1": 1,
                "Class_2": 2,
                "Class_3": 3,
                "Class_4": 4,
                "Class_5": 5,
                "Class_6": 6,
                "Class_7": 7,
                "Class_8": 8,
                "Class_9": 9}
after_mapping_target = data['target'].apply(lambda x: mapping_dict[x])

## 설명변수와 타겟변수를 분리, 학습데이터와 평가데이터 분리

In [13]:
feature_columns = list(data.columns.difference(['target'])) # target을 제외한 모든 행
X = data[feature_columns] # 설명변수
y = after_mapping_target # 타겟변수
train_x, test_x, train_y, test_y = train_test_split(X, y, test_size = 0.2, random_state = 42) # 학습데이터와 평가데이터의 비율을 8:2 로 분할| 
print(train_x.shape, test_x.shape, train_y.shape, test_y.shape) # 데이터 개수 확인

(49502, 93) (12376, 93) (49502,) (12376,)


## 1. XGBoost

In [14]:
# !pip install xgboost
import xgboost as xgb
import time
start = time.time() # 시작 시간 지정
xgb_dtrain = xgb.DMatrix(data = train_x, label = train_y) # 학습 데이터를 XGBoost 모델에 맞게 변환
xgb_dtest = xgb.DMatrix(data = test_x) # 평가 데이터를 XGBoost 모델에 맞게 변환
xgb_param = {'max_depth': 10, # 트리 깊이
         'learning_rate': 0.01, # Step Size
         'n_estimators': 100, # Number of trees, 트리 생성 개수
         'objective': 'multi:softmax', # 목적 함수
        'num_class': len(set(train_y)) + 1} # 파라미터 추가, Label must be in [0, num_class) -> num_class보다 1 커야한다.
xgb_model = xgb.train(params = xgb_param, dtrain = xgb_dtrain) # 학습 진행
xgb_model_predict = xgb_model.predict(xgb_dtest) # 평가 데이터 예측
print("Accuracy: %.2f" % (accuracy_score(test_y, xgb_model_predict) * 100), "%") # 정확도 % 계산
print("Time: %.2f" % (time.time() - start), "seconds") # 코드 실행 시간 계산

Accuracy: 76.67 %
Time: 23.36 seconds


In [15]:
xgb_model_predict

array([5., 3., 6., ..., 9., 2., 7.], dtype=float32)

## 2. LightGBM

In [16]:
# !pip install lightgbm
import lightgbm as lgb
start = time.time() # 시작 시간 지정
lgb_dtrain = lgb.Dataset(data = train_x, label = train_y) # 학습 데이터를 LightGBM 모델에 맞게 변환
lgb_param = {'max_depth': 10, # 트리 깊이
            'learning_rate': 0.01, # Step Size
            'n_estimators': 100, # Number of trees, 트리 생성 개수
            'objective': 'multiclass', # 목적 함수
            'num_class': len(set(train_y)) + 1} # 파라미터 추가, Label must be in [0, num_class) -> num_class보다 1 커야한다.
lgb_model = lgb.train(params = lgb_param, train_set = lgb_dtrain) # 학습 진행
lgb_model_predict = np.argmax(lgb_model.predict(test_x), axis = 1) # 평가 데이터 예측, Softmax의 결과값 중 가장 큰 값의 Label로 예측
print("Accuracy: %.2f" % (accuracy_score(test_y, lgb_model_predict) * 100), "%") # 정확도 % 계산
print("Time: %.2f" % (time.time() - start), "seconds") # 코드 실행 시간 계산

/usr/local/lib/python3.7/dist-packages/lightgbm/engine.py:118: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))


Accuracy: 73.57 %
Time: 16.37 seconds


In [17]:
lgb_model.predict(test_x)

array([[9.14195396e-16, 2.27101123e-02, 3.85432853e-01, ...,
        3.25763637e-02, 7.61804989e-02, 4.64683926e-02],
       [1.16264426e-15, 3.77262272e-02, 2.26739830e-01, ...,
        1.92812290e-01, 1.01826669e-01, 8.11988908e-02],
       [8.03061518e-16, 1.74144816e-02, 1.18616633e-01, ...,
        2.57008295e-02, 6.69196402e-02, 4.08194769e-02],
       ...,
       [8.35633463e-16, 5.03899675e-02, 1.67414994e-01, ...,
        4.81925245e-02, 1.02188157e-01, 3.95359380e-01],
       [1.01560525e-15, 2.13472780e-02, 4.60509516e-01, ...,
        3.32864538e-02, 8.46310485e-02, 5.16230380e-02],
       [8.92775603e-16, 2.04756016e-02, 1.31867900e-01, ...,
        4.13697353e-01, 1.44381292e-01, 4.53796283e-02]])

## 3. Catboost

In [19]:
!pip install catboost

     |████████████████████████████████| 76.3 MB 67 kB/s 


In [20]:
import catboost as cb
start = time.time() # 시작 시간 지정
cb_dtrain = cb.Pool(data = train_x, label = train_y) # 학습 데이터를 Catboost 모델에 맞게 변환
cb_param = {'max_depth': 10, # 트리 깊이
            'learning_rate': 0.01, # Step Size
            'n_estimators': 100, # Number of trees, 트리 생성 개수
            'eval_metric': 'Accuracy', # 평가 척도
            'loss_function': 'MultiClass'} # 손실 함수, 목적 함수
cb_model = cb.train(pool = cb_dtrain, params = cb_param) # 학습 진행
cb_model_predict = np.argmax(cb_model.predict(test_x), axis = 1) + 1 # 평가 데이터 예측, Softmax의 결과값 중 가장 큰 값의 Label로 예측, 인덱스의 순서를 맞추기 위해 +1
print("Accuracy: %.2f" % (accuracy_score(test_y, cb_model_predict) * 100), "%") # 정확도 % 계산
print("Time: %.2f" % (time.time() - start), "seconds") # 코드 실행 시간 계산

0:	learn: 0.5907034	total: 964ms	remaining: 1m 35s
1:	learn: 0.6356107	total: 2.02s	remaining: 1m 39s
2:	learn: 0.6411256	total: 2.95s	remaining: 1m 35s
3:	learn: 0.6480344	total: 3.87s	remaining: 1m 32s
4:	learn: 0.6508222	total: 4.77s	remaining: 1m 30s
5:	learn: 0.6499939	total: 5.67s	remaining: 1m 28s
6:	learn: 0.6507818	total: 6.58s	remaining: 1m 27s
7:	learn: 0.6548422	total: 7.49s	remaining: 1m 26s
8:	learn: 0.6559533	total: 8.39s	remaining: 1m 24s
9:	learn: 0.6560947	total: 9.28s	remaining: 1m 23s
10:	learn: 0.6568421	total: 10.2s	remaining: 1m 22s
11:	learn: 0.6588219	total: 11.1s	remaining: 1m 21s
12:	learn: 0.6592259	total: 12s	remaining: 1m 20s
13:	learn: 0.6611248	total: 12.9s	remaining: 1m 19s
14:	learn: 0.6625591	total: 13.8s	remaining: 1m 18s
15:	learn: 0.6631853	total: 14.7s	remaining: 1m 17s
16:	learn: 0.6639328	total: 15.6s	remaining: 1m 16s
17:	learn: 0.6668821	total: 16.5s	remaining: 1m 15s
18:	learn: 0.6669630	total: 17.4s	remaining: 1m 14s
19:	learn: 0.6675286	tot

In [ ]:
cb_model.predict(test_x)

array([[-0.34047199,  1.18951783,  0.4296545 , ..., -0.17528062,
        -0.02512535, -0.23089952],
       [-0.05653916,  0.45365426,  0.17195659, ...,  0.22287606,
         0.26190632,  0.18447355],
       [-0.31311   , -0.31539546, -0.31876501, ..., -0.29816626,
        -0.238871  , -0.3180434 ],
       ...,
       [ 0.04726952,  0.03794315, -0.17880234, ..., -0.2456077 ,
         0.11886516,  1.54034182],
       [-0.55746055,  1.77202298,  0.97862619, ..., -0.33775734,
        -0.48741853, -0.37792919],
       [-0.31665504,  0.08335556, -0.10060578, ...,  0.67896862,
         1.03198771, -0.14349506]])

In [21]:
# 데이터 불러오기
data = pd.read_csv("/content/drive/MyDrive/패캠 머신러닝/4주차 앙상블/2. Data/kc_house_data.csv") 
data.head() # 데이터 확인

id             date     price  ...  zipcode      lat     long
0  7129300520  20141013T000000  221900.0  ...    98178  47.5112 -122.257
1  6414100192  20141209T000000  538000.0  ...    98125  47.7210 -122.319
2  5631500400  20150225T000000  180000.0  ...    98028  47.7379 -122.233
3  2487200875  20141209T000000  604000.0  ...    98136  47.5208 -122.393
4  1954400510  20150218T000000  510000.0  ...    98074  47.6168 -122.045

[5 rows x 14 columns]

In [22]:
data = data.drop(['id', 'date', 'zipcode', 'lat', 'long'], axis = 1) # id, date, zipcode, lat, long  제거

In [23]:
feature_columns = list(data.columns.difference(['price'])) # Price를 제외한 모든 행
X = data[feature_columns]
y = data['price']
train_x, test_x, train_y, test_y = train_test_split(X, y, test_size = 0.3, random_state = 42) # 학습데이터와 평가데이터의 비율을 7:3
print(train_x.shape, test_x.shape, train_y.shape, test_y.shape) # 데이터 개수 확인

(15129, 8) (6484, 8) (15129,) (6484,)


In [24]:
# !pip install lightgbm
import lightgbm as lgb
start = time.time() # 시작 시간 지정
lgb_dtrain = lgb.Dataset(data = train_x, label = train_y) # 학습 데이터를 LightGBM 모델에 맞게 변환
lgb_param = {'max_depth': 10, # 트리 깊이
            'learning_rate': 0.01, # Step Size
            'n_estimators': 500, # Number of trees, 트리 생성 개수
            'objective': 'regression'} # 파라미터 추가, Label must be in [0, num_class) -> num_class보다 1 커야한다.
lgb_model = lgb.train(params = lgb_param, train_set = lgb_dtrain) # 학습 진행


/usr/local/lib/python3.7/dist-packages/lightgbm/engine.py:118: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))


In [32]:
from sklearn.metrics import mean_squared_error, r2_score
from math import sqrt

sqrt(mean_squared_error(lgb_model.predict(test_x),test_y))

214912.17539260507

In [26]:
import random
bagging_predict_result = [] # 빈 리스트 생성
for _ in range(10):
    data_index = [data_index for data_index in range(train_x.shape[0])] # 학습 데이터의 인덱스를 리스트로 변환
    random_data_index = np.random.choice(data_index, train_x.shape[0]) # 데이터의 1/10 크기만큼 랜덤 샘플링, // 는 소수점을 무시하기 위함
    print(len(set(random_data_index)))
    lgb_dtrain = lgb.Dataset(data = train_x.iloc[random_data_index,], label = train_y.iloc[random_data_index,]) # 학습 데이터를 LightGBM 모델에 맞게 변환
    lgb_param = {'max_depth': 14, # 트리 깊이
            'learning_rate': 0.01, # Step Size
            'n_estimators': 500, # Number of trees, 트리 생성 개수
            'objective': 'regression'} # 파라미터 추가, Label must be in [0, num_class) -> num_class보다 1 커야한다.
    lgb_model = lgb.train(params = lgb_param, train_set = lgb_dtrain) # 학습 진행
    predict1 = lgb_model.predict(test_x) # 테스트 데이터 예측
    bagging_predict_result.append(predict1) # 반복문이 실행되기 전 빈 리스트에 결과 값 저장

9559


/usr/local/lib/python3.7/dist-packages/lightgbm/engine.py:118: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))


9562
9538
9570
9606
9595
9561
9605
9605
9592


In [27]:
bagging_predict_result

[array([498691.75872444, 612650.05278405, 968195.10273884, ...,
        336995.79298313, 926280.59246654, 457323.80742761]),
 array([496370.17030026, 578506.25020959, 947341.56056006, ...,
        334157.42684464, 965596.53870321, 471470.43101516]),
 array([510846.20029807, 625200.79722371, 909382.4301396 , ...,
        332962.95016687, 892195.69015053, 448717.18514979]),
 array([525026.13007401, 668881.38056205, 906399.98447714, ...,
        336977.10748415, 940815.57854969, 472099.14088976]),
 array([ 533373.26696759,  638159.51157846, 1059593.83077794, ...,
         335553.60729196,  879859.42291662,  456964.1031009 ]),
 array([514505.3506031 , 665600.63536046, 950749.46283387, ...,
        349530.47159137, 939449.58729039, 461225.55226236]),
 array([512227.03162514, 615727.61187378, 888405.3814812 , ...,
        327940.59332336, 853729.80782168, 458477.99683518]),
 array([498216.94362818, 648562.69886538, 953061.51480336, ...,
        341081.74616358, 968582.57625733, 461401.363923

In [28]:
# Bagging을 바탕으로 예측한 결과값에 대한 평균을 계산
bagging_predict = [] # 빈 리스트 생성
for lst2_index in range(test_x.shape[0]): # 테스트 데이터 개수만큼의 반복
    temp_predict = [] # 임시 빈 리스트 생성 (반복문 내 결과값 저장)
    for lst_index in range(len(bagging_predict_result)): # Bagging 결과 리스트 반복
        temp_predict.append(bagging_predict_result[lst_index][lst2_index]) # 각 Bagging 결과 예측한 값 중 같은 인덱스를 리스트에 저장
    bagging_predict.append(np.mean(temp_predict)) # 해당 인덱스의 30개의 결과값에 대한 평균을 최종 리스트에 추가

In [29]:
# 예측한 결과값들의 평균을 계산하여 실제 테스트 데이트의 타겟변수와 비교하여 성능 평가

print("RMSE: {}".format(sqrt(mean_squared_error(bagging_predict, test_y)))) # RMSE

RMSE: 210728.78368185353


In [30]:
bagging_predict

[511783.99180972076,
 630712.2783535185,
 944535.7194905167,
 1585419.4308102273,
 635654.5222016845,
 372257.66120840964,
 711366.7492465803,
 424230.40065099683,
 461872.3462262976,
 496184.4876905417,
 636741.732126055,
 380960.099099844,
 300364.4939098092,
 360235.88376285706,
 339777.1684475307,
 1284582.2587532613,
 371377.97941887064,
 1008556.3470511917,
 318129.61365326215,
 526702.258171417,
 378116.3744994913,
 2041665.9389559045,
 655031.0300754658,
 538213.6624674683,
 506326.85735148675,
 479671.4954088008,
 296624.41455943725,
 250697.31797514507,
 474632.2936316288,
 536138.6838855885,
 491132.83763779595,
 472450.2985972557,
 461203.2163285885,
 593916.6796895489,
 377844.40870595275,
 1038154.1524193182,
 902635.760491523,
 530184.250596543,
 357637.88830172416,
 1523733.2153342657,
 390937.54640873376,
 276613.8309764671,
 507339.1989823749,
 342482.69777299144,
 255852.8375530825,
 242615.1741116874,
 335019.5270252496,
 334924.8468494055,
 354848.5222358845,
 5714