<p style="font-family: Arial; font-size:3.75em;color:black; font-style:bold"><br>
Numpy Tutorial
</p><br>


Reference: https://github.com/susanli2016/Machine-Learning-with-Python

핵심 내용:

- ndarrays: 계산의 편의를 위해 numpy에 내장되어있는 ndarray를 이용하는 함수
- Broadcasting: 사이즈가 다른 ndarray들의 계산을 위해서 numpy에 내장되어 있는 자동처리 함수 
- Input/Output: 파일 입출력.

조교
- 이정수 (KAIST AI 석사과정): bebeto@kaist.ac.kr
- 이상현 (KAIST AI 박사과정): shlee6825@kaist.ac.kr


<p style="font-family: Arial; font-size:3em;color:black; font-style:bold"><br>
Ndarray
</p><br>

In [1]:
import numpy as np                 # numpy를 np로 작성하는 것이 convention
array_1d = np.array([3, 33, 333])  
print(type(array_1d))

<class 'numpy.ndarray'>


In [2]:
# array의 shape 확인
print(array_1d.shape)               

(3,)


In [3]:
# array의 각 element 확인
print(array_1d[0], array_1d[1], array_1d[2]) 

3 33 333


In [4]:
# array의 첫번째 element를 바꾸기 
array_1d[0] =888            
print(array_1d)                        

[888  33 333]


In [6]:
array_2d = np.array([[11,12,13],
                     [21,22,23]])   

print(array_2d)  

[[11 12 13]
 [21 22 23]]


In [8]:
print("현재 array의 shape: ", array_2d.shape)                     
print("[0,0], [0,1], [1,0]의 값 확인: ", array_2d[0, 0], ", ",array_2d[0, 1],", ", array_2d[1, 0])

현재 array의 shape:  (2, 3)
[0,0], [0,1], [1,0]의 값 확인:  11 ,  12 ,  21


<p style="font-family: Arial; font-size:2em;color:black; font-style:bold"><br>
Numpy의 내장함수로 지정된 값으로 ndarray 만들기
</p><br>

- argument는 size를 넣어주는 것이 기본

In [9]:
import numpy as np

# zero vector 만들기 
zero_array = np.zeros((2,2))      
print(zero_array)                              

[[0. 0.]
 [0. 0.]]


In [12]:
# 값을 지정하여서 해당 값으로 채워진 ndarray 만들기 

full_array = np.full((2,2), 9.0)  # 1st argument: ndarray shape / 2nd argument: value 
print(full_array)   

[[9. 9.]
 [9. 9.]]


In [13]:
# 대각선이 1로 구성된 ndrray 만들기 
eye_array = np.eye(2,2)
print(eye_array)  

[[1. 0.]
 [0. 1.]]


In [14]:
# 1로만 구성된 ndarray 만들기 
one_array = np.ones((1,2))
print(one_array)

[[1. 1.]]


In [15]:
# 0~1 사이의 임의의 실수로 구성된 ndarray 만들기 
random_array = np.random.random((2,2))
print(random_array)    

[[0.28447427 0.33270876]
 [0.26845363 0.25799757]]


In [16]:
# 범위를 지정하여서 ndarray를 생성
# argument: (start), stop, (step). ()는 default가 0 / stop 미만의 수까지 
# 실제 사용 예시 : https://github.com/TreB1eN/InsightFace_Pytorch/blob/master/model.py, Line 276


arange_array = np.arange(3)
print(arange_array)

arange_array2 = np.arange(3,7)
print(arange_array2)

arange_array3 = np.arange(3,7,2)
print(arange_array3)

arange_array4 = np.arange(3,8,2)
print(arange_array4)

[0 1 2]
[3 4 5 6]
[3 5]
[3 5 7]


<p style="font-family: Arial; font-size:2em;color:black; font-style:bold"><br>
Array Indexing
</p><br>

In [17]:
import numpy as np

array = np.array([[11,12,13,14],
                     [21,22,23,24],
                     [31,32,33,34]])
print(array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [18]:
# 특정 row와 column만을 indexing
slice_array = array[:2, 1:3] # [row, column]
print(slice_array)

slice_array = array[2:, 2:4] # [row, column]
print(slice_array)

slice_array = array[:, 2:4] # [row, column]
print(slice_array)

slice_array = array[1:3, :] # [row, column]
print(slice_array)

[[12 13]
 [22 23]]
[[33 34]]
[[13 14]
 [23 24]
 [33 34]]
[[21 22 23 24]
 [31 32 33 34]]


In [20]:
# row와 column의 indexing ndarray를 생성
col_indices = np.array([0, 1, 1])
print('\nCol indices picked : ', col_indices)

row_indices = np.arange(3)
print('\nRows indices picked : ', row_indices)


Col indices picked :  [0 1 1]

Rows indices picked :  [0 1 2]


In [21]:
# 변화될 element의 row, col을 확인하기 위해 print
# zip 함수는 python 내장함수로써 짝을 지어주는 역할
for row,col in zip(row_indices,col_indices):
    print(row, ", ",col)

0 ,  0
1 ,  1
2 ,  1


In [22]:
print('이전 Array:')
print(array)
array[row_indices, col_indices] += 100000
print()
print('이후 Array:')
print(array)

이전 Array:
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]

이후 Array:
[[100011     12     13     14]
 [    21 100022     23     24]
 [    31 100032     33     34]]


<p style="font-family: Arial; font-size:2em;color:black; font-style:bold"><br>
Boolean Indexing
</p><br>

In [31]:
# create a 3x2 array
array = np.array([[11, 12], 
                  [21, 22], 
                  [31, 32]])
print(array)

[[11 12]
 [21 22]
 [31 32]]


In [32]:
# 우리가 원하는 조건에 맞춰서 ndarray를 재구성 
# 기존 array와 같은 크기의 Boolean value로 구성된 ndarray 생성
condition = (array > 15)
print(condition)

[[False False]
 [ True  True]
 [ True  True]]


In [33]:
# 실제 해당 값을 가진 ndarray를 출력 -> 1d array로 출력됨 
print(array[condition])

[21 22 31 32]


In [34]:
# 기존 shape을 유지하되 조건에 맞지 않는 값은 0으로 대체하고 싶은 경우 
# np.where 함수 사용 (condition, array, 대체 값)
# 실제 사용 예시 : https://github.com/kakaoenterprise/Learning-Debiased-Disentangled/blob/master/learner.py, Line 528
print(np.where(array>15, array, 0))

[[ 0  0]
 [21 22]
 [31 32]]


In [35]:
# condition에 해당하는 값을 직접 변경
array[condition] +=100
print(array)

[[ 11  12]
 [121 122]
 [131 132]]


<p style="font-family: Arial; font-size:2em;color:black; font-style:bold"><br>
Datatypes
</p><br>

In [36]:
#data type에 대한 설명: https://engineer-mole.tistory.com/85
ex1 = np.array([11, 12]) 
print(ex1.dtype)

int32


In [37]:
ex2 = np.array([11.0, 12.0]) 
print(ex2.dtype)

float64


In [38]:
ex3 = np.array([11, 21], dtype=np.int32) 
print(ex3.dtype)

int32


In [39]:
# 실수를 정수 형태로 변경
ex4 = np.array([11.1,12.7], dtype=np.int64)
print(ex4.dtype)
print()
print(ex4)

int64

[11 12]


In [40]:
# 정수를 실수 형태로 변경
ex5 = np.array([11, 21], dtype=np.float64)
print(ex5.dtype)
print()
print(ex5)

float64

[11. 21.]


<p style="font-family: Arial; font-size:2em;color:black; font-style:bold"><br>
Arithmetic Array Operation
</p><br>

In [41]:
x = np.array([[111,112],[121,122]], dtype=np.int)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


In [42]:
# add
print(x + y)         
print()
print(np.add(x, y))  

[[322.1 324.1]
 [342.1 344.1]]

[[322.1 324.1]
 [342.1 344.1]]


In [43]:
# subtract
print(x - y)
print()
print(np.subtract(x, y))

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [44]:
# multiply
print(x * y)
print()
print(np.multiply(x, y))

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [45]:
# divide
print(x / y)
print()
print(np.divide(x, y))

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [46]:
# square root
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [47]:
# exponent (e ** x)
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


In [48]:
# 두 행렬의 내적
x2d = np.array([[1,1],[1,1]])
y2d = np.array([[2,2],[2,2]])
print(x2d)
print(y2d)

[[1 1]
 [1 1]]
[[2 2]
 [2 2]]


In [49]:
print(x2d.dot(y2d))
print(np.dot(x2d, y2d))

[[4 4]
 [4 4]]
[[4 4]
 [4 4]]


In [50]:
# 두 벡터의 내적
a1d = np.array([9 , 9 ])
b1d = np.array([10, 10])

print(a1d)
print(b1d)

[9 9]
[10 10]


In [51]:
print(a1d.dot(b1d))
print(np.dot(a1d, b1d))

180
180


In [52]:
# 행렬과 벡터의 내적
print(x2d)
print(a1d)
print()
print(x2d.dot(a1d))
print(np.dot(x2d, a1d))

[[1 1]
 [1 1]]
[9 9]

[18 18]
[18 18]


In [53]:
# sum
ex1 = np.array([[11,12],[21,22]])
print(ex1)

print(np.sum(ex1))          # add all members

print(np.sum(ex1, axis=0))  # columnwise sum

print(np.sum(ex1, axis=1))  # rowwise sum

[[11 12]
 [21 22]]
66
[32 34]
[23 43]


In [54]:
# random array
x = np.random.randn(8)
print(x)

# another random array
y = np.random.randn(8)
print(y)

# returns element wise maximum between two arrays
print(np.maximum(x, y))

[-0.62672774  0.38139668 -1.45161492  0.70505457 -1.40412413  1.25840694
  1.57963137 -0.39419323]
[-0.45656256 -1.0418879  -0.92531505 -0.70799434  0.45852263 -0.66912643
 -0.61573618 -0.5742306 ]
[-0.45656256  0.38139668 -0.92531505  0.70505457  0.45852263  1.25840694
  1.57963137 -0.39419323]


In [55]:
# reshaping array
arr = np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [56]:
# reshape to be a 4 x 5 matrix
print(arr.reshape(4,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [57]:
# Transpose
ex1 = np.array([[11,12],[21,22]])
print(ex1)
print(ex1.T)

[[11 12]
 [21 22]]
[[11 21]
 [12 22]]


In [58]:
# where로 indexing
x_1 = np.array([1,2,3,4,5])
y_1 = np.array([11,22,33,44,55])
condition = np.array([True, False, True, False, True])

out = np.where(condition, x_1, y_1)
print(out)

[ 1 22  3 44  5]


In [59]:
mat = np.random.rand(5,5)
print(mat)
print(np.where( mat > 0.5, 1000, -1))
print(np.where( mat > 0.5, mat, -1))

[[0.72150736 0.56384386 0.52398707 0.87444062 0.30270962]
 [0.96028753 0.99700536 0.49080544 0.93460829 0.94304293]
 [0.63670524 0.04284037 0.237445   0.52189287 0.34926665]
 [0.6007764  0.43612541 0.28146519 0.94650273 0.66475631]
 [0.7013594  0.64061237 0.94515992 0.79714482 0.62238575]]
[[1000 1000 1000 1000   -1]
 [1000 1000   -1 1000 1000]
 [1000   -1   -1 1000   -1]
 [1000   -1   -1 1000 1000]
 [1000 1000 1000 1000 1000]]
[[ 0.72150736  0.56384386  0.52398707  0.87444062 -1.        ]
 [ 0.96028753  0.99700536 -1.          0.93460829  0.94304293]
 [ 0.63670524 -1.         -1.          0.52189287 -1.        ]
 [ 0.6007764  -1.         -1.          0.94650273  0.66475631]
 [ 0.7013594   0.64061237  0.94515992  0.79714482  0.62238575]]


In [60]:
# any/all condition
arr_bools = np.array([ True, False, True, True, False ])
print(arr_bools.any()) # True가 하나라도 있으면 True
print(arr_bools.all()) # 전부 True여야 True

True
False


In [61]:
# 임의의 수 생성
Y = np.random.normal(size = (3,5))
print(Y)

Z = np.random.randint(low=2,high=50,size=4)
print(Z)

[[-1.56820289  0.34393869  1.99788454 -0.15915573 -0.3292958 ]
 [ 0.72707416  1.60024596 -0.49816134 -0.13798748 -0.47642698]
 [-2.31799301  1.75386003  0.43941159 -0.06794592  0.25075213]]
[10  4 16 23]


In [62]:
print(np.random.permutation(Z))  #return a new ordering of elements in Z
print(np.random.uniform(size=4)) #uniform distribution
print(np.random.normal(size=4))  #normal distribution

[16 10 23  4]
[0.63617662 0.62919638 0.48049117 0.12038443]
[ 0.54609073 -0.35806447 -0.63330485 -0.23342606]


In [63]:
# ndarray 합치기 
K = np.random.randint(low=2,high=50,size=(2,2))
print(K)

print()
M = np.random.randint(low=2,high=50,size=(2,2))
print(M)

print(np.vstack((K,M)))                   # col-wise로 stack 
print(np.hstack((K,M)))                   # row-wise로 stack
print(np.concatenate([K, M], axis = 0))   # col-wise로 stack
print(np.concatenate([K, M.T], axis = 1)) # row-wise로 stack

[[30 34]
 [25 42]]

[[26 40]
 [ 6 15]]
[[30 34]
 [25 42]
 [26 40]
 [ 6 15]]
[[30 34 26 40]
 [25 42  6 15]]
[[30 34]
 [25 42]
 [26 40]
 [ 6 15]]
[[30 34 26  6]
 [25 42 40 15]]


<p style="font-family: Arial; font-size:2em;color:black; font-style:bold"><br>
Statistical Methods
<br><br>
</p>

In [64]:
# (2,4)의 임의의 실수로 구성된 행렬
arr = 10 * np.random.randn(2,5)
print(arr)

[[  2.65191341   5.27506907   1.36238507 -18.4478122   -1.35065713]
 [-10.33974614  21.83261376  -1.264419    16.2339      -0.49848   ]]


In [65]:
# 모든 수의 평균
print(arr.mean())

1.5454766835432514


In [66]:
# 행으로 평균 구하기
print(arr.mean(axis = 1))

[-2.10182036  5.19277372]


In [67]:
# 열로 평균 구하기
print(arr.mean(axis = 0))

[-3.84391637 13.55384142  0.04898303 -1.1069561  -0.92456857]


In [68]:
# 모든 수의 합
print(arr.sum())

15.454766835432514


In [69]:
# 행으로 중앙값 구하기
print(np.median(arr, axis = 1))

[ 1.36238507 -0.49848   ]


<p style="font-family: Arial; font-size:2em;color:black; font-style:bold"><br>
Sorting
<br><br>
</p>

In [70]:
# 임의의 1d-array 생성
unsorted_array = np.random.randn(10)
print(unsorted_array)

[-0.89257604  1.36056058 -0.959507   -0.26204956 -1.30310533 -2.05737158
 -1.13332134  0.86287644  0.16042361 -0.20992106]


In [71]:
# ndarray 복사 후 sorting 진행
sorted_array = np.array(unsorted_array)
sorted_array.sort()

print('이전 unsorted:', unsorted_array)
print()
print('이후 sorted:', sorted_array)

이전 unsorted: [-0.89257604  1.36056058 -0.959507   -0.26204956 -1.30310533 -2.05737158
 -1.13332134  0.86287644  0.16042361 -0.20992106]

이후 sorted: [-2.05737158 -1.30310533 -1.13332134 -0.959507   -0.89257604 -0.26204956
 -0.20992106  0.16042361  0.86287644  1.36056058]


In [72]:
array = np.array([1,2,1,4,2,1,4,2])

print(np.unique(array))

[1 2 4]


<p style="font-family: Arial; font-size:2em;color:black; font-style:bold"><br>
Set Operations
<br><br>
</p>

In [73]:
s1 = np.array(['desk','chair','bulb'])
s2 = np.array(['lamp','bulb','chair'])
print(s1, s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [75]:
print( np.intersect1d(s1, s2) ) # 교집합

['bulb' 'chair']


In [76]:
print( np.union1d(s1, s2) ) # 합집합

['bulb' 'chair' 'desk' 'lamp']


In [77]:
print( np.setdiff1d(s1, s2) ) # s1-s2

['desk']


In [78]:
print(np.in1d(s1, s2)) # s1에 s1과 s2 공통적으로 있는 element가 있는지에 대한 boolean ndarray

[False  True  True]


<p style="font-family: Arial; font-size:3em;color:black; font-style:bold"><br>
Broadcasting
<br><br>
</p>

In [79]:
import numpy as np

# original array 생성
original_array = np.zeros((4,3))
print(original_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [80]:
# 더할 ndarray
add_rows = np.array([1, 0, 2])
print(add_rows)

[1 0 2]


In [81]:
# original array에 add_rows를 더함
''' 
original array (4,3)과 add_rows (3,)의 shape이 다름
-> numpy의 broadcasting이 (3,)을 자동적으로 (4,3)으로 변형후 덧셈을 진행
'''
result = original_array + add_rows  
print(result)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [85]:
# 행단위가 아닌 열단위로도 진행
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T

print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [86]:
result = original_array + add_cols 
print(result)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [87]:
add_scalar = np.array([1])  
print(original_array+add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Example from the slides:

In [88]:
# 3x4 matrix
arrA = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])
print(arrA)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [89]:
# 4x1 array
arrB = [0,1,0,2]
print(arrB)

[0, 1, 0, 2]


In [90]:
# 두 행렬의 덧셈
print(arrA + arrB)

[[ 1  3  3  6]
 [ 5  7  7 10]
 [ 9 11 11 14]]


<p style="font-family: Arial; font-size:3em;color:black; font-style:bold"><br>
파일 입출력
<br><br>
</p>

<p style="font-family: Arial; font-size:2em;color:black; font-style:bold"><br>
Binary format
<br><br>
</p>

In [74]:
x = np.array([ 23.23, 24.24] )

In [75]:
import os
os.makedirs('./data', exist_ok=True) # data라는 폴더 생성

In [76]:
np.save('./data/array.npy', x)

In [77]:
np.load('./data/array.npy')

array([23.23, 24.24])

<p style="font-family: Arial; font-size:2em;color:black; font-style:bold"><br>
Text format
<br><br>
</p>

In [78]:
np.savetxt('./data/array.txt', X=x, delimiter=',')

In [79]:
np.loadtxt('./data/array.txt', delimiter=',')

array([23.23, 24.24])