# Pytorch
 - Define-by-Run

# Pytorch Packages

 - **torch**
 - torch.autograd
 - torch.nn
 - torch.optim
 - torch.multiprocessing
 - torch.utils
 - torch.legact

# Pytorch Tensor Basic Usage

- Create Tensor
- Indexing, Joining, Slicing
- Initialization
- Math Operations

## 1. Create Tensor

### 1) random numbers

In [2]:
from __future__ import print_function
import torch

In [3]:
# torch.rand(size)
# 0~1 사이의 연속균등분포에서 값을 뽑아 5x3 텐서를 생성합니다. ~U(0,1)
x = torch.rand(2,3)
x

tensor([[0.1701, 0.4176, 0.4813],
        [0.7902, 0.3517, 0.1521]])

In [4]:
# torch.randn(size)
# randn의 경우 평균은 0, 표준편차는 1인 정규분포에서 값을 가져옵니다. ~z(0,1)
x = torch.randn(2,3)
x

tensor([[ 0.5096,  0.5142, -1.9999],
        [-0.8417,  2.0529, -1.9370]])

In [5]:
# torch.randperm(n)
# 0부터 n-1까지 1씩 늘어나며 값을 랜덤으로 정렬합니다.
x = torch.randperm(5)
x

tensor([3, 1, 2, 4, 0])

### 2) empty, zeros, ones, arange, max

In [6]:
# torch.empty(size)
# 원하는 크기의 아주 작은 값을 가진 텐서를 생성합니다. dtype은 input에 따라 결정됩니다.
x = torch.empty(2,3)
x[0]

tensor([0., 0., 0.])

In [7]:
x.size()

torch.Size([2, 3])

In [8]:
# torch.zeros(size)
# 원하는 크기의 0 값을 가진 텐서를 생성합니다.
x = torch.zeros(2,3)
x[0]

tensor([0., 0., 0.])

In [9]:
# torch.ones(size)
# 원하는 크기의 1의 값을 가진 텐서를 생성합니다.
x = torch.ones(2,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
# torch.arange(start,end,step=1)
# start값부터 end값 전까지 step만큼 더하며 텐서를 생성합니다.
x = torch.arange(0,3,step=0.5)
x

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])

In [11]:
x.size()

torch.Size([6])

In [12]:
# torch.max(input, dim, keepdim=False, out=None) -> (Tensor, LongTensor)
# tensor의 최대값을 산출합니다.

x = torch.rand(2,3)
print(x)

tensor([[0.6282, 0.9602, 0.1559],
        [0.2190, 0.9144, 0.1071]])


In [13]:
# 최대값을 출력합니다.
print(torch.max(x))

tensor(0.9602)


In [14]:
# 해당 차원에서 최대값과 그 위치를 출력합니다.
print(torch.max(x,0))

torch.return_types.max(
values=tensor([0.6282, 0.9602, 0.1559]),
indices=tensor([0, 0, 0]))


In [15]:
print(torch.max(x,0)[1])
print(x.size(), torch.max(x,0)[1].size())

tensor([0, 0, 0])
torch.Size([2, 3]) torch.Size([3])


In [16]:
# 위치를 출력합니다.
print(torch.max(x,1)[1])
print(x.size(), torch.max(x,1)[1].size())

tensor([1, 1])
torch.Size([2, 3]) torch.Size([2])


### 3) Tensor Data Type

| Data type               | dtype                                         | Tensor types                 |
|:-------------------------|:-----------------------------------------------|:------------------------------|
| 32-bit floating point   | ``` torch.float32 ``` or ``` torch.float ```  | ``` torch.*.FloatTensor ```  |
| 64-bit floating point   | ``` torch.float64 ``` or ``` torch.double ``` | ``` torch.*.DoubleTensor ``` |
| 16-bit floating point   | ``` torch.float16 ``` or ``` torch.half ```   | ``` torch.*.HalfTensor ```   |
| 16-bit integer (signed) | ``` torch.int16 ``` or ``` torch.short ```    | ``` torch.*.ShortTensor ```  |
| 32-bit integer (signed) | ``` torch.int32 ``` or ``` torch.int ```      | ``` torch.*.IntTensor ```    |
| 64-bit integer (signed) | ``` torch.int64 ``` or ``` torch.long ```     | ``` torch.*.LongTensor ```   |

In [17]:
# torch.empty(size, dtype=)
# torch.zeros(size, dtype=)
# torch.arange(start,end,dtype=)

# torch에서 지원하는 다양한 data type을 옵션으로 지정할 수 있습니다.

x = torch.empty(2,3, dtype=torch.float)
y = torch.zeros(2,3, dtype = torch.long)
z = torch.arange(0,3,step=0.5,dtype=torch.double)

print(x)
print(y)
print(z)

tensor([[0.0000e+00, 0.0000e+00, 1.8754e+28],
        [1.6634e-04, 3.3379e-09, 1.0017e-11]])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000], dtype=torch.float64)


In [18]:
# torch.tensor(size or list, dtype = torch.floattensor) 
# 원하는 텐서를 바로 생성합니다.
x = torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

In [19]:
# torch.FloatTensor(size or list)
x = torch.FloatTensor(2,3)
print(x)
x = torch.FloatTensor([2,3])
print(x)

tensor([[6.5987e-10, 5.2010e+22, 1.7012e-04],
        [8.2651e+20, 1.7661e-04, 1.7569e-04]])
tensor([2., 3.])


In [20]:
# tensor.type_as(tensor_type)
# tensor 형 변환
x = x.type_as(torch.IntTensor())
x

tensor([2, 3], dtype=torch.int32)

### 4) Tensor Size

In [21]:
# tensor.size()

x = torch.FloatTensor(10,12,3,3)

print(x.size()[:])
print(x.size()[0])

torch.Size([10, 12, 3, 3])
10


In [22]:
x = x.new_ones(5,3, dtype=torch.double) #5,3 차원의 새로운 텐서를 생성합니다.
print(x)

x = torch.randn_like(x,dtype=torch.float) # 같은 size에서 랜덤한 숫자로 채워진 텐서를 생성합니다.
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.3135, -0.1796, -0.0919],
        [-0.9608,  0.0934,  0.7494],
        [-0.1063,  1.0101,  0.8616],
        [ 0.8200,  0.4531,  1.0230],
        [ 1.2428,  0.0956,  1.2582]])


## 2. Math Operations

### 1) add, mul, div

In [23]:
# torch.add()
# 텐서의 값끼리 더합니다.

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
add = torch.add(x1, x2)

x1,x2,add,x1+x2,x1-x2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]),
 tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [24]:
#차원이 다르더라도 안쪽 차원만 같으면 연산이 가능합니다.

x = torch.rand(1,5,3)
y = torch.rand(5,3)
x, y, torch.add(x,y)

(tensor([[[0.8745, 0.1264, 0.5578],
          [0.5085, 0.3228, 0.0403],
          [0.0317, 0.5080, 0.6637],
          [0.8976, 0.9249, 0.9416],
          [0.6367, 0.2211, 0.4067]]]),
 tensor([[0.7982, 0.3354, 0.3530],
         [0.4745, 0.7215, 0.1915],
         [0.5908, 0.7549, 0.1164],
         [0.1693, 0.6511, 0.8130],
         [0.4678, 0.6907, 0.3784]]),
 tensor([[[1.6727, 0.4619, 0.9108],
          [0.9830, 1.0443, 0.2318],
          [0.6225, 1.2629, 0.7801],
          [1.0669, 1.5760, 1.7546],
          [1.1045, 0.9118, 0.7851]]]))

In [25]:
# torch.add 말고 add_의 경우에는 이러한 연산 기능이 지원되지 않습니다. 따라서 먼저 x를 같은 차원으로 바꿔줍니다.

x = torch.rand(5,3)
y.add_(x)
print(y)

tensor([[1.5215, 1.0577, 0.8486],
        [0.9068, 1.4721, 0.6033],
        [1.5680, 1.1129, 0.6752],
        [0.4042, 0.9407, 1.3499],
        [1.2987, 1.0079, 1.3674]])


In [26]:
# x 텐서의 2열을 불러옵니다. numpy 연산이 지원됩니다.

print(x)
print(x.shape)
print(x[:,1])
print(x[:,1].shape)

tensor([[0.7233, 0.7222, 0.4956],
        [0.4323, 0.7506, 0.4119],
        [0.9772, 0.3580, 0.5588],
        [0.2350, 0.2896, 0.5369],
        [0.8309, 0.3172, 0.9890]])
torch.Size([5, 3])
tensor([0.7222, 0.7506, 0.3580, 0.2896, 0.3172])
torch.Size([5])


In [27]:
# torch.mul()
# hadamard product, mxn, mxn 행렬 2개를 곱합니다. 덧셈에 대해 분배법칙을 따릅니다.

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
x3 = torch.mul(x1,x2)

x1.size(), x2.size(), x3.size(), x1, x2, x3

(torch.Size([2, 3]),
 torch.Size([2, 3]),
 torch.Size([2, 3]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[ 1.,  4.,  9.],
         [16., 25., 36.]]))

In [28]:
# torch.mul()

x1 = torch.FloatTensor([[1,2,3,],[4,5,6]])
x2 = x1*10

x2

tensor([[10., 20., 30.],
        [40., 50., 60.]])

In [29]:
# torch.div()

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
x3 = torch.div(x1,x2)

x3

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [30]:
# torch.div()

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])

x1/5

tensor([[0.2000, 0.4000, 0.6000],
        [0.8000, 1.0000, 1.2000]])

### 2) pow, exp, log

In [31]:
# torch.pow(input,exponent)

x1 = torch.rand(3,4)

print(x1)
print(torch.pow(x1,2),"\n",x1**2)

tensor([[0.6177, 0.9263, 0.8878, 0.6755],
        [0.7432, 0.3092, 0.3120, 0.2481],
        [0.2051, 0.2203, 0.8755, 0.9731]])
tensor([[0.3815, 0.8581, 0.7882, 0.4563],
        [0.5523, 0.0956, 0.0974, 0.0615],
        [0.0421, 0.0485, 0.7665, 0.9469]]) 
 tensor([[0.3815, 0.8581, 0.7882, 0.4563],
        [0.5523, 0.0956, 0.0974, 0.0615],
        [0.0421, 0.0485, 0.7665, 0.9469]])


In [32]:
# torch.exp(tensor,out=None)

x1 = torch.rand(3,4)

print(x1)
print(torch.exp(x1))

tensor([[0.6796, 0.1640, 0.1401, 0.0880],
        [0.1693, 0.5753, 0.7464, 0.4079],
        [0.9512, 0.2618, 0.8862, 0.3835]])
tensor([[1.9732, 1.1782, 1.1503, 1.0920],
        [1.1845, 1.7776, 2.1094, 1.5036],
        [2.5888, 1.2993, 2.4260, 1.4675]])


In [33]:
# torch.log(input,out=None)

x1 = torch.rand(3,4)

print(x1)
print(torch.log(x1))

tensor([[0.1220, 0.6496, 0.1690, 0.7384],
        [0.9962, 0.8965, 0.4360, 0.6686],
        [0.5736, 0.2889, 0.4120, 0.6208]])
tensor([[-2.1040, -0.4314, -1.7780, -0.3032],
        [-0.0039, -0.1093, -0.8302, -0.4025],
        [-0.5558, -1.2417, -0.8867, -0.4768]])


In [34]:
# torch.mm(matrix1, matrix2)

x1 = torch.rand(3,4)
x2 = torch.rand(4,5)

torch.mm(x1,x2)

tensor([[1.5903, 0.6861, 1.2484, 0.6551, 0.7264],
        [2.1172, 1.1261, 1.5901, 0.8421, 1.1505],
        [2.2740, 0.8766, 1.6422, 0.9312, 1.4007]])

In [35]:
# torch.bmm(batch_matrix1, batch_matrix2)

x1 = torch.rand(10,3,4)
x2 = torch.rand(10,4,5)

torch.bmm(x1,x2).size()

torch.Size([10, 3, 5])

![img](https://github.com/shwksl101/Pytorch-A-to-Z/blob/master/img/innerproduct.PNG?raw=true)

In [36]:
# torch.dot(tensor1, tensor2)

torch.dot(torch.tensor([2,3]), torch.tensor([2,1]))

tensor(7)

In [37]:
# torch.t(matrix)
# tranpose

x1 = torch.rand(3,4)
print(x1.size(), x1.t().size())

torch.Size([3, 4]) torch.Size([4, 3])


In [38]:
# torch.transpose(input,dim0,dim1)

x1 = torch.rand(10,3,4)
x1.size(), torch.transpose(x1,1,2).size(), x1.transpose(1,2).size() #contiguous

(torch.Size([10, 3, 4]), torch.Size([10, 4, 3]), torch.Size([10, 4, 3]))

In [39]:
# torch.eig(a,eigenvectors=Flase)
# eigen_value, eigen_vector

x1 = torch.rand(2,2)

print(x1,"\n",torch.eig(x1,True))

tensor([[0.2847, 0.4695],
        [0.3372, 0.8015]]) 
 torch.return_types.eig(
eigenvalues=tensor([[0.0687, 0.0000],
        [1.0175, 0.0000]]),
eigenvectors=tensor([[-0.9084, -0.5395],
        [ 0.4180, -0.8420]]))


C:\Users\chahn\anaconda3\lib\site-packages\ipykernel_launcher.py:6: UserWarning: torch.eig is deprecated in favor of torch.linalg.eig and will be removed in a future PyTorch release.
torch.linalg.eig returns complex tensors of dtype cfloat or cdouble rather than real tensors mimicking complex tensors.
L, _ = torch.eig(A)
should be replaced with
L_complex = torch.linalg.eigvals(A)
and
L, V = torch.eig(A, eigenvectors=True)
should be replaced with
L_complex, V_complex = torch.linalg.eig(A) (Triggered internally at  ..\aten\src\ATen\native\BatchLinearAlgebra.cpp:2894.)
  


### 3) view, item

In [40]:
# view()

x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8) # -1의 경우 다른 차원들로 유추합니다. 이 경우에는 2로 유추합니다.
print(x.size())
print(y.size(),y)
print(z.size(),z)

torch.Size([4, 4])
torch.Size([16]) tensor([-0.0429, -0.5700,  1.2483, -0.4653, -0.9397,  0.9915,  0.0812, -0.3595,
         0.7307, -1.1383, -0.3131, -0.4981,  1.3516, -0.8189, -0.7255, -0.2356])
torch.Size([2, 8]) tensor([[-0.0429, -0.5700,  1.2483, -0.4653, -0.9397,  0.9915,  0.0812, -0.3595],
        [ 0.7307, -1.1383, -0.3131, -0.4981,  1.3516, -0.8189, -0.7255, -0.2356]])


In [41]:
# item()

x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.0081])
-0.008097464218735695


- 더 많은 연산은 다음의 링크에서 참고하세요 https://pytorch.org/docs/stable/torch.html

## 3. Tensor to Numpy, Numpy to Tensor

In [42]:
import numpy as np

In [43]:
a = torch.ones(5) # 1로 채워진 텐서를 생성합니다.
print(a)

tensor([1., 1., 1., 1., 1.])


In [44]:
# tensor.numpy()

b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [45]:
# torch.from_numpy(ndarray)

a = np.ones(5) #a와 b는 연동됩니다.
b = torch.from_numpy(a)

np.add(a,1,out=a)

print(a)
print(b) #chartensor를 제외한 모든 tensor는 numpy로의 변환을 지원합니다.

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## 4. Tensor on GPU

In [51]:
torch.cuda.is_available()

False

In [46]:
x= torch.FloatTensor([[1,2,3],[4,5,6]])

if torch.cuda.is_available():
    x_cuda = x.cuda()
else:
    x_cuda = x.cpu()
    
print(x_cuda)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [48]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    
    y = torch.ones_like(x,device=device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to("cpu")) #.to 기능을 tensor를 GPU로 연산할 수 있습니다
    print(z.to("cuda"))

## 5. Indexing, Slicing, Joining

### 1) Indexing

In [49]:
# tensor.index_select(input,dim,index)

x = torch.rand(4,3)
out = torch.index_select(x,0,torch.LongTensor([0,3]))
# index는 꼭 Longtensor로 입력해야 합니다.

print(x.size(), out.size())
print(x, "\n", out)

torch.Size([4, 3]) torch.Size([2, 3])
tensor([[0.8150, 0.3505, 0.5999],
        [0.8743, 0.9959, 0.2999],
        [0.1668, 0.0766, 0.0298],
        [0.4448, 0.3116, 0.9180]]) 
 tensor([[0.8150, 0.3505, 0.5999],
        [0.4448, 0.3116, 0.9180]])


In [50]:
print(x.size(),'\n', x)
print(x[:,0].size(),x[:,0])
print(x[0,:].size(),x[0,:])
print(x[0:2,0:2].size(),'\n', x[0:2,0:2])

torch.Size([4, 3]) 
 tensor([[0.8150, 0.3505, 0.5999],
        [0.8743, 0.9959, 0.2999],
        [0.1668, 0.0766, 0.0298],
        [0.4448, 0.3116, 0.9180]])
torch.Size([4]) tensor([0.8150, 0.8743, 0.1668, 0.4448])
torch.Size([3]) tensor([0.8150, 0.3505, 0.5999])
torch.Size([2, 2]) 
 tensor([[0.8150, 0.3505],
        [0.8743, 0.9959]])


### 2) Joining

In [55]:
# torch.cat(seq, dim=0)
# dim을 기준으로 tensor를 합칩니다.
# dim = 0은 행, dim = 1은 열 기준입니다.

x = torch.FloatTensor([[1,2,3],
                       [4,5,6]])
y = torch.FloatTensor([[7,8,9],
                       [10,11,12]])
z1 = torch.cat([x,y],dim = 0)
z2 = torch.cat([x,y],dim = 1)

print(x)
print(y)
print(z1)
print(z2)
print(z1.shape)
print(z2.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  7.,  8.,  9.],
        [ 4.,  5.,  6., 10., 11., 12.]])
torch.Size([4, 3])
torch.Size([2, 6])


In [56]:
# torch.stack(sequence,dim=0)
# dim을 기준으로 쌓습니다.

x = torch.FloatTensor([1,2,3])
x_stack = torch.stack([x,x],dim=0)
x_stack2 = torch.stack([x,x],dim=1)

print(x_stack,"\n",x_stack2)

tensor([[1., 2., 3.],
        [1., 2., 3.]]) 
 tensor([[1., 1.],
        [2., 2.],
        [3., 3.]])


### 3) Slicing

In [57]:
# torch.chunk(tensor, chunks, dim=0)
# tensor를 chunk 단위로 쪼갭니다. chunk 개수 만큼 생성합니다.

x = torch.FloatTensor([[1,2,3],
                       [4,5,6]])
y = torch.FloatTensor([[7,8,9],
                       [10,11,12]])
z1 = torch.cat([x,y],dim = 0)

x_1, x_2 = torch.chunk(z1,2,dim=0)
y_1, y_2, y_3 = torch.chunk(z1,3,dim=1)

print(z1)
print(x_1)
print(x_2)
print(y_1)
print(y_2)
print(y_3)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[ 1.],
        [ 4.],
        [ 7.],
        [10.]])
tensor([[ 2.],
        [ 5.],
        [ 8.],
        [11.]])
tensor([[ 3.],
        [ 6.],
        [ 9.],
        [12.]])


In [58]:
# torch.split(tensor,split_size,dim=0) 각 size가 split_size만큼인 것을 생성합니다.

x = torch.FloatTensor([[1,2,3],
                       [4,5,6]])
y = torch.FloatTensor([[7,8,9],
                       [10,11,12]])
z1 = torch.cat([x,y],dim = 0)

x1,x2 = torch.split(z1,2,dim=0)
y1,y2 = torch.split(z1,2,dim=1)

print(z1)
print(x1)
print(x2)
print(y1)
print(y2)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])
tensor([[ 3.],
        [ 6.],
        [ 9.],
        [12.]])


### 4) squeezing

In [59]:
# torch.squeeze(input, dim=None)
# 1짜리 차원을 줄입니다.

x1 = torch.FloatTensor(10,1,3,1,4)
x2 = torch.squeeze(x1)

x1.size(), x2.size()

(torch.Size([10, 1, 3, 1, 4]), torch.Size([10, 3, 4]))

In [60]:
# torch.unsqueeze(input,dim=None)
# 1짜리 차원을 더합니다.

x1 = torch.FloatTensor(10,3,4)
x2 = torch.unsqueeze(x1,dim=0)

x.size(), x2.size()

(torch.Size([2, 3]), torch.Size([1, 10, 3, 4]))

## 6. Initialization

In [61]:
import torch.nn.init as init

x1 = init.uniform_(torch.FloatTensor(3,4),a=0,b=9) 
x2 = init.normal_(torch.FloatTensor(3,4),std=0.2)
x3 = init.constant_(torch.FloatTensor(3,4),3.1415)

x1,x2,x3

(tensor([[0.2278, 1.6377, 1.5546, 0.4370],
         [6.2398, 5.1019, 4.0935, 4.4221],
         [1.5991, 3.1642, 5.5248, 3.8579]]),
 tensor([[ 0.1656, -0.3534, -0.2269, -0.0502],
         [ 0.0690,  0.1194,  0.1975,  0.0682],
         [-0.1657,  0.3465,  0.1830,  0.0878]]),
 tensor([[3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415]]))